= Lyrically - A Spring Cloud Function/Alexa Skill Sample

Lyrically is a Spring Cloud Function application for deployment to AWS Lambda that produces Speechlet response JSON. That means that it can be triggered as the backing function for an Alexa Skill.

This project does not make use of Spring Skills.

Once the function is deployed to AWS Lambda and the skill is defined you should be able to use it with any of the following utterances:

 * _Alexa, ask Lyrically to give me a lyric_
 * _Alexa, ask Lyrically to recite a lyric_
 * _Alexa, ask Lyrically to say some lyrics_

Alexa will reply by reciting the first few lines of lyrics from a randomly chosen 1980's song.

== Building and Running the Function Locally

To build the application:

[source,sh]
----
$ mvn clean package
----

To run locally:

[source,sh]
----
$ mvn spring-boot:run
----

Then...

[source,sh]
----
$ curl localhost:8080/lyrics
----

You should see an Speechlet response similar to the following:

[source,sh]
----
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> Johnny used to work on the dock. Union went on strike. He's down on his luck. It's tough. So tough. </speak>"
    },
    "card": {
      "type": "Simple",
      "title": "Lyrically",
      "content": "Johnny used to work on the dock. Union went on strike. He's down on his luck. It's tough. So tough."
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}
----

== Deploying the Function to AWS Lambda

Before deploying to Lambda, you'll need to create a role for the function:

[source,sh]
----
TODO
----

To deploy the application to AWS Lambda (the previously created role should be given to the `--role` parameter):

[source,sh]
----
$ aws lambda create-function --function-name lyrics --role arn:aws:iam::494442948374:role/service-role/mySpeechRole --zip-file fileb://target/lyrically-0.0.1-SNAPSHOT-aws.jar --handler org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler --description "Lyrically: Spring Cloud Function + Alexa Example" --runtime java8 --region us-east-1 --timeout 30 --memory-size 1024 --publish
----

If you make changes, build the project again, then:

[source,sh]
----
aws lambda update-function-code --function-name=lyrics --zip-file fileb://target/lyrically-0.0.1-SNAPSHOT-aws.jar
----

== Defining the Alexa Skill

TODO
